---
- hosts: all
  remote_user: ubuntu
  tasks:
    - name: 'Install apache2'
      apt:
        name: apache2
        state: absent
        update_cache: yes
      sudo: yes
    - name: 'Restart service'
      service:
        name: apache2
        state: restarted
      sudo: yes
      
