---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: create "{{ item }}" user
      user:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        update_password: on_create
        password: "{{ item.password }}"
      with_items:
        - { name: 'pavan', password: 'pavan44', state: 'absent' }
        - { name: 'vinay', password: 'vinay44', state: 'absent' }
        - { name: 'madhu', password: 'madhu44', state: 'present' }
