---
- hosts: all
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: 'install apache'
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: 'restart apache2'
  handlers:
     - name: 'restart apache2'
       service:
          name: apache2
          state: restarted
          
