---
- hosts: all
  remote_user: ubuntu

  tasks:
    - name: Install nginx on Debian
      apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes
      tags: install
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes
      tags: start
    - name: stop nginx
      service:
        name: nginx
        state: stopped
      become: yes
      tags: stop
